ClinicManagementSystem/Controllers/AppointmentController.cs
using ClinicManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;

namespace ClinicManagementSystem.Controllers
{
    
    public class AppointmentController : Controller
    {
      private readonly AppDbContext _context;
        public AppointmentController(AppDbContext context)
        {
            _context=context;
        }
        public IActionResult AddEditAppointment(int? id)
        {
         
            ViewBag.ActiveDoctors = _context.Doctors
                .Where(d => d.IsActive)
                .Select(d => new SelectListItem
                {
                    Value = d.Doctor_Id.ToString(),
                    Text = d.Name
                })
                .ToList();

         
            if (id.HasValue)
            {
                var findAppointment = _context.Appointments
              .SingleOrDefault(a => a.Appointment_Id == id.Value);

                if (findAppointment == null)
                {
                   
                    return NotFound();
                }

                return View(findAppointment);
            }

      
          
                return View(new Appointment());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEditAppointment(Appointment appoint)
        {
            ViewBag.ActiveDoctors = _context.Doctors
                  .Where(d => d.IsActive).Select(d =>
                  new SelectListItem
                  {
                      Value = d.Doctor_Id.ToString(),
                      Text = d.Name
                  }).ToList();

           


            if (appoint.Appointment_Id == 0)
            {


                appoint.Date = DateTime.Now;
                appoint.Time = DateTime.Now.TimeOfDay;
                appoint.TokenNumber = GenerateDialyToken();
                _context.Appointments.Add(appoint);
                _context.SaveChanges();

            }

            else
            {
              
            
                var existingappoint = _context.Appointments.SingleOrDefault(a => a.Appointment_Id == appoint.Appointment_Id);

                if (existingappoint == null)
                {
                    return NotFound();
                }

                existingappoint.Patient_Name = appoint.Patient_Name;
                existingappoint.Patient_Contact = appoint.Patient_Contact;
                existingappoint.Doctor_Id = appoint.Doctor_Id;
                existingappoint.Fee = appoint.Fee;

                _context.Appointments.Update(existingappoint);


                _context.SaveChanges();
             }
            
        
          

        

            return RedirectToAction("Index","Home");
        }

        public IActionResult GetAllAppointment()
        {
            var GetAll =_context.Appointments.OrderByDescending(a=>a.Appointment_Id).Include(d=>d.Doctor).ToList();

            return View(GetAll);
        }

        public IActionResult DeleteAppointment(int id)
        {
            var findAppointment = _context.Appointments.SingleOrDefault(a => a.Appointment_Id == id);

            if(findAppointment != null)
            {
                _context.Appointments.Remove(findAppointment);
                 _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        private string GenerateDialyToken()
        {
            var today = DateTime.Today;

            var todayTokens = _context.Appointments
                .Where(a => a.Date.Date == today && a.TokenNumber.StartsWith("A-"))
                .Select(a => a.TokenNumber)
                .ToList();

            if (!todayTokens.Any())
                return "A-001";

          
            int maxNumber = todayTokens
                .Select(t => int.Parse(t.Split('-')[1]))
                .Max();

            return $"A-{(maxNumber + 1).ToString("D3")}";
        }

       
    }
}

ClinicManagementSystem/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ClinicManagementSystem.Models;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagementSystem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly AppDbContext _context;
    public HomeController(ILogger<HomeController> logger,AppDbContext context)
    {
        _context = context;
        _logger = logger;
    }

    public IActionResult Index()
    {
        var today = DateTime.Today;
        var tomorrow = today.AddDays(1);

        var appointments = _context.Appointments
            .Where(a => a.Date >= today && a.Date < tomorrow)
            .Include(a => a.Doctor)
            .OrderByDescending(a => a.Appointment_Id)
            .ToList();

        //Count No of active Doctors at that time
        ViewBag.Doctors =_context.Doctors.Where(d => d.IsActive == true).Count();

        //Count No of Appoinments of that day
        ViewBag.Appointments = _context.Appointments.Where(a => a.Date == DateTime.Today).Count();

        //Count Total No of Doctors in Clinic
        ViewBag.TotalDoc = _context.Doctors.Count();

        return View(appointments);
    }

 

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ClinicManagementSystem/Views/Home/Index.cshtml
@model List<ClinicManagementSystem.Models.Appointment>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container align-content-center">
    <h2 class="text-primary text-center fw-bold">Welcome,To Our Clinic System</h2>
    <div class="row mt-5 justify-content-center">
        <div class="col-lg-4">
            <div class="card bg-warning p-3 pt-4">
                <h4>Total Doctors</h4>
                @{
                    if (ViewBag.TotalDoc == 0)
                    {
                        <h6>No Data Yet!</h6>
                    }
                    else
                    {
                    <h6>@ViewBag.TotalDoc</h6>
                        
                    }
                  }
            </div>
        </div> 

        <div class="col-lg-4">
            <div class="card bg-success p-3 pt-4">
                <h4>Available Doctors</h4>
                @{
                if (ViewBag.Doctors == 0)
                {
                        <h6>No Data Yet!</h6>
                    }
                    else
                    {
                        
                    <h6>@ViewBag.Doctors</h6>
                    }
                 }
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card bg-primary p-3 pt-4">
                <h4>Today Appointments</h4>
                @{
                 if (ViewBag.Appointments == 0)
                {
                        <h6>No Data Yet!</h6>
                    }
                    else
                    {
                        
                    <h6>@ViewBag.Appointments</h6>
                    }
                    }
            </div>
        </div>

    </div> @*row div end*@

    <div class="container mt-5 align-content-center">
        <h2 class="text-primary">Today All Appointments</h2>
        <table class="table table-hover mt-3 table-responsive">
            <thead>
                <tr>
                    <th>Patient Name</th>
                    <th>Patient Contact</th>
                    <th>Doctor Name</th>
                    <th>Checkup Fee</th>
                    <th>Date & Time</th>
                    
                    <th>Token Number</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr> <th>No Records Yet!</th> </tr>
                }
                @foreach(var a in Model)
                {
                    <tr>
                        <td>@a.Patient_Name</td>
                        <td>@a.Patient_Contact</td>
                        <td>@a.Doctor.Name</td>
                        <td>Rs. @a.Fee</td>
                        <td>@a.Date</td>
                       
                        <td>@a.TokenNumber</td>
                        <td><a asp-route-id="@a.Appointment_Id" asp-action="AddEditAppointment" asp-controller="Appointment" class="btn btn-warning">Edit</a></td>

                        <td><a asp-route-id="@a.Appointment_Id" asp-action="DeleteAppointment" asp-controller="Appointment" class="btn btn-danger">Delete</a></td>
                    </tr>
                }
            </tbody>

        </table>

    </div> @*container div end*@

</div>@*main container div end*@